:schedule:
  check_openpilot_pull_requests:
    cron: '30 */1 * * *'
    class: CheckOpenpilotPullRequestsWorker
  check_openpilot_contributors:
    cron: '0 */1 * * *'
    class: CheckOpenpilotContributorsWorker
  check_openpilot_repos:
    cron: '15 */1 * * *'
    class: CheckOpenpilotReposWorker
  check_openpilot_releases:
    cron: '45 */1 * * *'
    class: CheckOpenpilotReleases