:schedule:
  check_openpilot_pull_requests:
    cron: '0 4 * * *'
    class: CheckOpenpilotPullRequestsWorker
  check_openpilot_contributors:
    cron: '0 5 * * *'
    class: 
  check_openpilot_repos:
    cron: '0 6 * * *'
    class: CheckOpenpilotReposWorker